language: python
cache: ccache
sudo: required
dist: trusty

compiler:
  - gcc
services:
  - docker
os:
  - linux
env:
  - JOB=LR_TEST

addons:
  apt:
    packages:
      - git
      - python
      - python-pip
  #ssh_known_hosts: 13.229.163.131

before_install:
  - sudo pip install -U virtualenv pre-commit pip
  - docker pull paddlepaddle/paddle:latest

script:
  - exit_code=0
  - docker run -i --rm -v "$PWD:/epep_test" paddlepaddle/paddle:latest /bin/bash -c
    'rm /bin/sh && ln -s /bin/bash /bin/sh; cd /epep_test; ./test/lr_test.sh'

notifications:
  email:
    on_success: change
    on_failure: always
